In [1]:
import pandas as pd

In [2]:
!ls

content.csv  correlations.csv  dig_data.ipynb  kaggle  switch  topics.csv

In [6]:
!ls switch

README.md      content_3.csv	   topic2string_3.pkl  topics_3.csv
content_0.csv  topic2string_0.pkl  topics_0.csv
content_1.csv  topic2string_1.pkl  topics_1.csv
content_2.csv  topic2string_2.pkl  topics_2.csv

In [17]:
!ls kaggle

README.md	content.csv	  sample_submission.csv
Untitled.ipynb	correlations.csv  topics.csv

In [19]:
pd.read_csv('kaggle/correlations.csv')

             topic_id                                        content_ids
0      t_00004da3a1b2  c_1108dd0c7a5d c_376c5a8eb028 c_5bc0e1e2cba0 c...
1      t_00068291e9a4  c_639ea2ef9c95 c_89ce9367be10 c_ac1672cdcd2c c...
2      t_00069b63a70a                                     c_11a1dc0bfb99
3      t_0006d41a73a8  c_0c6473c3480d c_1c57a1316568 c_5e375cf14c47 c...
4      t_0008768bdee6       c_34e1424229b4 c_7d1a964d66d5 c_aab93ee667f4
...               ...                                                ...
61512  t_fff830472691                      c_61fb63326e5d c_8f224e321c87
61513  t_fff9e5407d13  c_026db653a269 c_0fb048a6412c c_20de77522603 c...
61514  t_fffbe1d5d43c                      c_46f852a49c08 c_6659207b25d5
61515  t_fffe14f1be1e                                     c_cece166bad6a
61516  t_fffe811a6da9                                     c_92b8fad372ee

[61517 rows x 2 columns]

In [18]:
pd.read_csv('kaggle/sample_submission.csv')

         topic_id                                        content_ids
0  t_00004da3a1b2  c_1108dd0c7a5d c_376c5a8eb028 c_5bc0e1e2cba0 c...
1  t_00068291e9a4  c_639ea2ef9c95 c_89ce9367be10 c_ac1672cdcd2c c...
2  t_00069b63a70a                                     c_11a1dc0bfb99
3  t_0006d41a73a8  c_0c6473c3480d c_1c57a1316568 c_5e375cf14c47 c...
4  t_4054df11a74e                      c_3695c5dc1df6 c_f2d184a98231

In [7]:
pd.read_csv('switch/content_0.csv')

,id,title,description,kind,text,language,copyright_holder,license,fold,language_t
0,c_00002381196d,"Sumar números de varios dígitos: 48,029+233,930","Suma 48,029+233,930 mediante el algoritmo está...",video,NaN,es,NaN,NaN,3 6,es
1,c_000087304a9e,Trovare i fattori di un numero,Sal trova i fattori di 120.,video,NaN,it,NaN,NaN,2,it
2,c_0000ad142ddb,Sumar curvas de demanda,Cómo añadir curvas de demanda,video,NaN,es,NaN,NaN,5,es
3,c_0000c03adc8d,Nado de aproximação,Neste vídeo você vai aprender o nado de aproxi...,document,Nado de aproximação Saber nadar nas ondas sem...,pt,Sikana Education,CC BY-NC-ND,2,pt
4,c_00016694ea2a,geometry-m3-topic-a-overview.pdf,geometry-m3-topic-a-overview.pdf,document,Estándares Comunes del Estado de Nueva York P...,es,Engage NY,CC BY-NC-SA,2 3,es
...,...,...,...,...,...,...,...,...,...,...
154042,c_fffcbdd4de8b,2. 12: Diffusion,NaN,html5,What will eventually happen to these dyes? Th...,en,CSU and Merlot,CC BY-NC-SA,8,en
154043,c_fffe15a2d069,Sommare facendo gruppi da 10,Sal somma 5+68 spezzando il 5 in un 2 e un 3.,video,NaN,it,NaN,NaN,4,it
154044,c_fffed7b0d13a,Introdução à subtração,Sal fala sobre o que significa subtrair. Os ex...,video,NaN,pt,NaN,NaN,5,pt
154045,c_ffff04ba7ac7,SA of a Cone,NaN,video,NaN,en,NaN,NaN,4,en
154046,c_ffffe5254266,The Jats,NaN,video,NaN,en,NaN,NaN,5,en

In [8]:
pd.read_csv('switch/topics_0.csv')

,id,title,description,channel,category,level,language,parent,has_content,fold,language_t
0,t_00004da3a1b2,Откриването на резисторите,"Изследване на материали, които предизвикват на...",000cf7,source,4,bg,t_16e29365b50d,True,0,bg
1,t_000095e03056,Unit 3.3 Enlargements and Similarities,NaN,b3f329,aligned,2,en,t_aa32fb6252dc,False,-1,en
2,t_00068291e9a4,Entradas e saídas de uma função,Entenda um pouco mais sobre funções.,8e286a,source,4,pt,t_d14b6c2a2b70,True,0,pt
3,t_00069b63a70a,Transcripts,NaN,6e3ba4,source,3,en,t_4054df11a74e,True,0,en
4,t_0006d41a73a8,Графики на експоненциални функции (Алгебра 2 н...,Научи повече за графиките на сложните показате...,000cf7,source,4,bg,t_e2452e21d252,True,1,bg
...,...,...,...,...,...,...,...,...,...,...,...
76967,t_fffb0bf2801d,4.3 Graph of functions,NaN,e77b55,aligned,4,en,t_676e6a1a4dc7,False,-1,en
76968,t_fffbe1d5d43c,Inscribed shapes problem solving,Use properties of inscribed angles to prove pr...,0c929f,source,4,sw,t_50145b9bab3f,True,2,sw
76969,t_fffe14f1be1e,Lección 7,NaN,6e90a7,aligned,6,es,t_d448c707984d,True,8,es
76970,t_fffe811a6da9,تحديد العلاقة بين الإحداثيّات القطبية والإحداث...,5b9e5ca86571f90499ea987f,9fd860,source,2,ar,t_5b4f3ba4eb7d,True,2,ar
76971,t_fffe88835149,Formation of shadows and eclipses (umbra and p...,NaN,c7ca13,aligned,4,en,t_988923176459,False,-1,en

In [10]:
import pickle
topic2string_0=pickle.load(open('switch/topic2string_0.pkl','rb'))

In [16]:
cnt=0
for i in topic2string_0:
    cnt+=1
    if cnt>5:
        break
    print(i)
    print(topic2string_0[i])
    print('=======')

t_00004da3a1b2
Откриването на резисторите # Открития и проекти # Физика # Наука # Khan Academy (български език) # Изследване на материали, които предизвикват намаление в отклонението, когато се свържат последователно с нашия измервателен уред.
=======
t_000095e03056
Unit 3.3 Enlargements and Similarities # Junior High Level 3 # Ghana JHS Curriculum (in progress) #
=======
t_00068291e9a4
Entradas e saídas de uma função # Álgebra: funções # 9º Ano # Matemática por ano (Alinhada à BNCC) # Khan Academy (Português (Brasil)) # Entenda um pouco mais sobre funções.
=======
t_00069b63a70a
Transcripts # Flow Charts: Logical Thinking? # Engineering # MIT Blossoms #
=======
t_0006d41a73a8
Графики на експоненциални функции (Алгебра 2 ниво) # Показателни и логаритмични функции # Алгебра (цялото съдържание) # Математика # Khan Academy (български език) # Научи повече за графиките на сложните показателни функции от вида y=a*b^(x+c)+d.
=======

In [12]:
pd.read_csv('content.csv')

,id,title,description,kind,text,language,copyright_holder,license,fold
0,c_00002381196d,"Sumar números de varios dígitos: 48,029+233,930","Suma 48,029+233,930 mediante el algoritmo está...",video,NaN,es,NaN,NaN,3 6
1,c_000087304a9e,Trovare i fattori di un numero,Sal trova i fattori di 120.\n\n,video,NaN,it,NaN,NaN,2
2,c_0000ad142ddb,Sumar curvas de demanda,Cómo añadir curvas de demanda\n\n,video,NaN,es,NaN,NaN,5
3,c_0000c03adc8d,Nado de aproximação,Neste vídeo você vai aprender o nado de aproxi...,document,\nNado de aproximação\nSaber nadar nas ondas ...,pt,Sikana Education,CC BY-NC-ND,2
4,c_00016694ea2a,geometry-m3-topic-a-overview.pdf,geometry-m3-topic-a-overview.pdf,document,Estándares Comunes del Estado de Nueva York\n\...,es,Engage NY,CC BY-NC-SA,2 3
...,...,...,...,...,...,...,...,...,...
154042,c_fffcbdd4de8b,2. 12: Diffusion,NaN,html5,What will eventually happen to these dyes?\n\n...,en,CSU and Merlot,CC BY-NC-SA,8
154043,c_fffe15a2d069,Sommare facendo gruppi da 10,Sal somma 5+68 spezzando il 5 in un 2 e un 3.\n\n,video,NaN,it,NaN,NaN,4
154044,c_fffed7b0d13a,Introdução à subtração,Sal fala sobre o que significa subtrair. Os ex...,video,NaN,pt,NaN,NaN,5
154045,c_ffff04ba7ac7,SA of a Cone,NaN,video,NaN,en,NaN,NaN,4
154046,c_ffffe5254266,The Jats,NaN,video,NaN,en,NaN,NaN,5

In [5]:
pd.read_csv('topics.csv')

,id,title,description,channel,category,level,language,parent,has_content,fold
0,t_00004da3a1b2,Откриването на резисторите,"Изследване на материали, които предизвикват на...",000cf7,source,4,bg,t_16e29365b50d,True,0
1,t_000095e03056,Unit 3.3 Enlargements and Similarities,NaN,b3f329,aligned,2,en,t_aa32fb6252dc,False,-1
2,t_00068291e9a4,Entradas e saídas de uma função,Entenda um pouco mais sobre funções.,8e286a,source,4,pt,t_d14b6c2a2b70,True,0
3,t_00069b63a70a,Transcripts,NaN,6e3ba4,source,3,en,t_4054df11a74e,True,0
4,t_0006d41a73a8,Графики на експоненциални функции (Алгебра 2 н...,Научи повече за графиките на сложните показате...,000cf7,source,4,bg,t_e2452e21d252,True,1
...,...,...,...,...,...,...,...,...,...,...
76967,t_fffb0bf2801d,4.3 Graph of functions,NaN,e77b55,aligned,4,en,t_676e6a1a4dc7,False,-1
76968,t_fffbe1d5d43c,Inscribed shapes problem solving,Use properties of inscribed angles to prove pr...,0c929f,source,4,sw,t_50145b9bab3f,True,2
76969,t_fffe14f1be1e,Lección 7,NaN,6e90a7,aligned,6,es,t_d448c707984d,True,8
76970,t_fffe811a6da9,تحديد العلاقة بين الإحداثيّات القطبية والإحداث...,5b9e5ca86571f90499ea987f,9fd860,source,2,ar,t_5b4f3ba4eb7d,True,2
76971,t_fffe88835149,Formation of shadows and eclipses (umbra and p...,NaN,c7ca13,aligned,4,en,t_988923176459,False,-1

In [4]:
pd.read_csv('correlations.csv')

,topic_id,content_ids,language,level,category,parent,fold
0,t_00004da3a1b2,c_1108dd0c7a5d c_376c5a8eb028 c_5bc0e1e2cba0 c...,bg,4,source,t_16e29365b50d,0
1,t_00068291e9a4,c_639ea2ef9c95 c_89ce9367be10 c_ac1672cdcd2c c...,pt,4,source,t_d14b6c2a2b70,0
2,t_00069b63a70a,c_11a1dc0bfb99,en,3,source,t_4054df11a74e,0
3,t_0006d41a73a8,c_0c6473c3480d c_1c57a1316568 c_5e375cf14c47 c...,bg,4,source,t_e2452e21d252,1
4,t_0008768bdee6,c_34e1424229b4 c_7d1a964d66d5 c_aab93ee667f4,gu,4,supplemental,t_0da7a331d666,0
...,...,...,...,...,...,...,...
61512,t_fff830472691,c_61fb63326e5d c_8f224e321c87,en,4,source,t_c75d6acecf78,8
61513,t_fff9e5407d13,c_026db653a269 c_0fb048a6412c c_20de77522603 c...,es,2,supplemental,t_5bd8f6ae9f7d,7
61514,t_fffbe1d5d43c,c_46f852a49c08 c_6659207b25d5,sw,4,source,t_50145b9bab3f,2
61515,t_fffe14f1be1e,c_cece166bad6a,es,6,aligned,t_d448c707984d,8
61516,t_fffe811a6da9,c_92b8fad372ee,ar,2,source,t_5b4f3ba4eb7d,2